### PR TITLE
PR: Replace setup.py package name by pywinpty

### LINKED ISSUE #18: Change package name to be pywinpty
The module name is `winpty` but the package is named pywinpty.

We should have both names be the same, in this case I would lean towards `pywinpty`

@ccordoba12 what do you think?

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #18

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 I did not understand you show pyzmq and zmq as an example? but you agree with the change or not?

**Comment by goanpeca** [comment]
I dont undertsand... the pypi package is pywinptyy but the setup was wrong?/?

**Comment by andfoy** [comment]
Yes, I actually forgot to send these changes to upstream

**Comment by goanpeca** [comment]
ok

**Comment by ccordoba12** [comment]
The Python package name was wrong but the module name is right.

See: https://github.com/zeromq/pyzmq

**Comment by goanpeca** [comment]
ok

**Comment by ccordoba12** [comment]
@andfoy, don't forget to remove `winpty` from PyPi.

**Comment by goanpeca** [comment]
That is what I was saying... @andfoy uploaded it correctly...
https://pypi.python.org/pypi/pywinpty

There was never a https://pypi.python.org/pypi/winpty package... I think he forgot to make a PR. That is the reason for making PRs as opposed to working directly on branches ;-)

**Comment by ccordoba12** [comment]
What? Very confusing!! @andfoy, please be more careful for next time!

**Comment by andfoy** [comment]
Sorry, when I uploaded those wheels the changes were made locally and never got to be even on my fork.

**Pull request merged**
