### PR TITLE
PR: Update README usage documentation

### LINKED ISSUE #27: Update README usage documentation

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #27

### CODE REVIEW

**Comment by andfoy** [comment]
Is there any section that we may need to add/update @goanpeca?

**Comment by ccordoba12** [comment]
The coverage badge is missing. Let me activate it in coveralls.io

**Comment by ccordoba12** [comment]
I'm afraid you'll have to add it. I don't have admin permissions here ;-)

Just log with your Github account and add the repo. Once you do that, you need to look for the repo token and add it to `appveyor.yml` as env var.

**Comment by ccordoba12** [comment]
The process is exactly the same as the one in `spyder-terminal`.

**Comment by ccordoba12** [comment]
Where is `appveyor.yml` in this repo? I don't understand how the tests are running...

**Comment by andfoy** [comment]
@goanpeca is on charge of CI integration

**Pull request merged**
